# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [3]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [4]:
import numpy as np

**2. Print the numpy version and the configuration**

In [12]:
print(np.version.full_version)
print(np.show_config())

1.16.6
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Zirya/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Zirya/anaconda3/envs/ensf-ml\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Zirya/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_l

**3. Create a 1D array of zeros of size 10 of type float32**

In [253]:
np.zeros(10, dtype=np.single)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [18]:
Z = np.zeros((32,12))
print("Memory allocation of:", Z.nbytes, "bytes")

Memory allocation of: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [19]:
arr = np.arange(10,59)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [20]:
a = np.arange(10)
# Include your solution below
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [21]:
threeD = np.arange(0,9).reshape(3,3)
print(threeD)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [22]:
threeDi = np.identity(3)
print(threeDi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [256]:
Z = np.random.random((10,11))
# Include your solution below
print(Z.max(axis=0))

[0.92269736 0.99121034 0.83227465 0.97045013 0.96222655 0.89115746
 0.99272382 0.72943545 0.79870733 0.96546214 0.95183287]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [28]:
one_border = np.ones((7,7))
one_border[1:-1,1:-1] = 0
print(one_border)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [43]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, 2, 'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [31]:
Z = np.random.uniform(0,10,10)
print(Z)
# Include your solution below
print(Z.astype(int))

[8.14476654 0.42531339 7.80994568 0.07583276 5.28666446 6.67230348
 4.383868   4.45405025 0.39494807 7.8101068 ]
[8 0 7 0 5 6 4 4 0 7]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [54]:
a = np.arange(0,5)
a = a + np.zeros((5,5)) 
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [260]:
a = np.linspace(0.1,1,10,endpoint=False)
print(a)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


**15. Create a random vector of size 10 and sort it**

In [261]:
rand_sort = np.random.rand(10)
rand_sort.sort()
print(rand_sort)

[0.07509315 0.09322656 0.24036211 0.31831852 0.45352554 0.49438131
 0.52327716 0.63373918 0.75883717 0.98497456]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [271]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt((X**2)+(Y**2))
T = np.arctan(Y / X)
print("Radius", R)
print("Angle (radians)", T)
print("Angle (degrees)", np.rad2deg(T))

Radius [1.18202905 0.86663833 0.43016364 0.62135227 1.01880946 0.8860609
 0.9089614  1.20453593 0.93235241 0.51155836]
Angle (radians) [0.75485635 0.79842519 1.54953699 0.32743251 0.37264752 0.76727091
 0.48985022 0.70710274 0.9160536  1.240399  ]
Angle (degrees) [43.25008273 45.74639384 88.78192996 18.76050078 21.35113018 43.96138504
 28.06635038 40.51400275 52.48600482 71.06962769]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [277]:
b = np.random.rand(10)
print("The maximum value in array b:", b.max(), "\n")
print("array b:",b, "\n")
b[b == b.max()] = 0
print("After replacing max value in b with 0:", b)

The maximum value in array b: 0.9635376169704527 

array b: [0.03989213 0.40593185 0.51563063 0.96353762 0.24982211 0.507737
 0.06617411 0.7655539  0.51914669 0.41415869] 

After replacing max value in b with 0: [0.03989213 0.40593185 0.51563063 0.         0.24982211 0.507737
 0.06617411 0.7655539  0.51914669 0.41415869]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [278]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
# Include your solution below
print(Z[np.abs(Z-z).argmin()])

[0.30577943 0.53302644 0.73091968 0.56257821 0.28856955 0.050547
 0.63476016 0.47075725 0.10061224 0.82386248]
0.47075724956943454


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [279]:
Z = np.arange(0,5)[::-1]
# Include your solution below
x = 3
z = np.zeros((len(Z)-1)*x + len(Z))
z[::(x+1)] = Z
print(z)

[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [280]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
print(np.transpose(A) * np.transpose(B))

[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [281]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="./Figures/bbox.png" width="150" /> 

In [301]:
def bbox(img):
    #include your solution below
    r = np.nonzero(img)
    return (np.min(r[0]), np.min(r[1])), (np.max(r[0]), np.max(r[1]))

from PIL import Image

img = np.array(Image.open('./Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [218]:
def moving_average(x,N = 3):
    return np.sum(np.resize(x, ((int)(len(x)/N), N)), axis=1) / N

a = np.arange(30)
print("Input array:", a)
N = 3
print(moving_average(a,N))

Input array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [239]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
print(np.repeat(np.arange(len(C)), C))

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [249]:
Z = np.random.randint(0,10,50)
# Include your solution below
print(Z)
print(Z[np.bincount(Z).argmax()])

[7 1 9 7 8 6 5 9 9 0 8 2 2 6 0 5 0 5 7 3 4 6 3 3 0 4 4 9 7 7 6 5 0 9 6 5 8
 1 7 0 4 1 4 5 8 4 4 9 9 0]
7


**26. Write a function to return the n largest values of an array** 

In [303]:
def nlargest(a,n = 5):
    # Include your solution here
    test = np.sort(a, axis=None)[::-1]
    return test[:n]

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9999 9998 9997 9996 9995]
