# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

**1. Import the numpy package under the name np**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [2]:
print("numpy package version:", np.version.full_version)
print(np.show_config())

numpy package version: 1.16.6
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/tobi/opt/anaconda3/envs/ensf-ml/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/U

**3. Create a 1D array of zeros of size 10 of type float32**

In [3]:
np.zeros(10, dtype=np.single)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [4]:
Z = np.zeros((32,12))
print("Memory allocation of:", Z.nbytes, "bytes")

Memory allocation of: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [5]:
arr = np.arange(10,59)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [6]:
a = np.arange(10)
# Include your solution below
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [7]:
threeD = np.arange(0,9).reshape(3,3)
print(threeD)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [8]:
threeDi = np.identity(3)
print(threeDi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [9]:
Z = np.random.random((10,11))
# Include your solution below
print(Z.max(axis=0)) # Finds maximum value normal to the x (0) axis, which is the max value in each column

[0.92255523 0.99435402 0.94426613 0.97513761 0.99276392 0.83472126
 0.9798112  0.85022884 0.96903303 0.68514175 0.75247912]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [10]:
one_border = np.ones((7,7))
one_border[1:-1,1:-1] = 0
print(one_border)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [11]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, 2, 'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [12]:
Z = np.random.uniform(0,10,10)
# Include your solution below
print(Z.astype(int))

[2 7 6 2 3 3 2 9 0 9]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [13]:
a = np.arange(0,5)
a = a + np.zeros((5,5)) 
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [14]:
a = np.linspace(0.1,1,10,endpoint=False)
print(a) # If zero were to be included, could specify 0 as the starting value in the linspace function

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


**15. Create a random vector of size 10 and sort it**

In [15]:
rand_sort = np.random.rand(10)
rand_sort.sort() # Uses quick sort as the default algorithm
print(rand_sort)

[0.2010554  0.27224543 0.39883662 0.40976376 0.44065213 0.49473777
 0.52056278 0.52318189 0.91932835 0.96242366]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [16]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt((X**2)+(Y**2))
T = np.arctan(Y / X) # tangent inverse
print("Radius:\n", R)
print("Angle (radians):\n", T) # Calculated angle in both radians and degrees as units were not specified
print("Angle (degrees):\n", np.rad2deg(T))

Radius:
 [1.12991076 0.72976293 0.8749581  0.83088321 0.91580747 1.10772618
 1.06579136 0.71357778 1.35632001 0.26778892]
Angle (radians):
 [0.76255831 0.31907197 0.59771042 0.41686752 0.56345954 1.04442731
 0.95862185 0.90090121 0.75254869 1.55973926]
Angle (degrees):
 [43.69137264 18.28147752 34.24628462 23.88474961 32.2838535  59.84127708
 54.92498635 51.61783682 43.11786362 89.36647688]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [17]:
b = np.random.rand(10)
print("The maximum value in array b:", b.max(), "\n")
print("array b:",b, "\n")
b[b == b.max()] = 0
print("After replacing max value in b with 0:", b)

The maximum value in array b: 0.9708852540442708 

array b: [0.29975966 0.13209574 0.37074922 0.44843186 0.04206368 0.68670966
 0.36384094 0.97088525 0.45170093 0.72238889] 

After replacing max value in b with 0: [0.29975966 0.13209574 0.37074922 0.44843186 0.04206368 0.68670966
 0.36384094 0.         0.45170093 0.72238889]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [18]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
# Include your solution below
print("Closest value to", z, "is:", Z[np.abs(Z-z).argmin()])

[0.39975909 0.37362159 0.86207786 0.27204991 0.39375925 0.15987049
 0.93949621 0.22227026 0.90084185 0.17862412]
Closest value to 0.5 is: 0.399759088403273


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [19]:
Z = np.arange(0,5)[::-1] # Please note that the code provided DOES NOT generate a vector like [5,4,3,2,1]
# as the starting point is included and endpoint is exluded, producing the vector [4,3,2,1,0] 
# Include your solution below
x = 3
z = np.zeros((len(Z)-1)*x + len(Z))
z[::(x+1)] = Z
print(z)

[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [20]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
print(np.transpose(A) * np.transpose(B)) # Element-wise multiplication NOT dot-product

[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [21]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
W[[0,1]] = W[[1,0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="./Figures/bbox.png" width="150" /> 

In [22]:
def bbox(img):
    #include your solution below
    r = np.nonzero(img) # Where could have also been easily used, where 1==True, True represents a white pixel
    return (np.min(r[0]), np.min(r[1])), (np.max(r[0]), np.max(r[1]))

from PIL import Image

img = np.array(Image.open('./Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [23]:
def moving_average(x,N = 3):
    try:
        return np.sum(np.resize(x, ((int)(len(x)/N), N)), axis=1) / N
    except:
        return "n/a, '{}' is an invalid value for N".format(N)

a = np.arange(30)
print("Input array:", a)
N = 3 
print("Sliding window average: ", moving_average(a,N))

Input array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Sliding window average:  [ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [24]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
print("Inverse of bincount (i.e. original array): ", np.repeat(np.arange(len(C)), C))

[0 2 1 1 2 0 1]
Inverse of bincount (i.e. original array):  [1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [25]:
Z = np.random.randint(0,10,50)
# Include your solution below
print("Original array:", Z)
print("Most frequent value:", Z[np.bincount(Z).argmax()])

Original array: [1 1 2 2 8 4 8 1 9 2 4 0 5 7 8 7 2 8 8 9 9 2 2 6 4 3 6 3 1 2 8 5 4 6 0 0 6
 0 0 8 5 4 1 3 8 8 4 4 8 6]
Most frequent value: 9


**26. Write a function to return the n largest values of an array** 

In [26]:
def nlargest(a,n = 5):
    # Include your solution here
    test = np.sort(a, axis=None)[::-1]
    try:
        return test[:n]
    except:
        return "'{}' is an invalid value for n".format(n) 

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9999 9998 9997 9996 9995]
